### PR TITLE
Feat/45 use DESCRIPTION

### PR DESCRIPTION
**Pull request by AlexAxthelm**
Remove imports.R and use DESCRIPTION to manage dependencies instead.

### CODE REVIEW

**Comment by jdhoffa** [comment]
Also closes #53 I think? @cjyetman

**Review by jdhoffa — APPROVED** [review]
lgtm!

**Comment by cjyetman** [comment]
FYI @jdhoffa I think this does *not* close #53 because the DESCRIPTION includes the PACTA packages and the Dockerfile uses `pak::local_install_deps()`

**Review by cjyetman — APPROVED** [review]

**Comment by AlexAxthelm** [comment]
#53 is next on my list.

**Comment by jdhoffa** [comment]
Thanks both!!

**Pull request merged**
